name: Deploy app to gh-pages

on:
  # Manually trigger the workflow
  workflow_dispatch:
  # Trigger on push to `main` branch
  push:
    branches: ["main"]
  # Trigger on pull request to all branches (but do not deploy to gh-pages)
  pull_request:

jobs:
  shinylive:
    uses: posit-dev/r-shinylive/.github/workflows/deploy-app.yaml@actions-v1
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
